const MERCURYO_BUY_CURRENCY = "USDT";
const MERCURYO_BUY_NETWORK_BIG = "TRON";
const MERCURYO_BUY_NETWORK_SMALL = "TRON";
module.exports = {
  MERCURYO_BUY_CURRENCY,
  MERCURYO_BUY_NETWORK_BIG,
  MERCURYO_BUY_NETWORK_SMALL,
};
